#!/bin/bash
#
# Kool-server Start kool-server service
#
# chkconfig: 2345 80 10
# description: Kool monkey server
# processname: kool-server
# config: /opt/kool_monkey/conf/kool-server.conf
# pidfile: /opt/kool_monkey/run/kool-server.pid

PATH=/opt/kool_monkey/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
CONFIG_FILE=/opt/kool_monkey/conf/kool-server.conf
DAEMON_PATH=/opt/kool_monkey/bin
DESC="Kool monkey server"

case "$1" in
	start)
		echo -n "Starting $DESC: "
		su monkey -c "$DAEMON_PATH/kool-server &"
		sleep 1
		;;
	stop)
		echo -n "Stopping $DESC: "
		su monkey -c "pkill kool-server"
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
